export const comunas = ['Alhue', 'Buin', 'Calera De Tango', 'Cerrillos', 'Cerro Navia', 'Colina', 
'Conchalí', 'El Bosque', 'Estacion Central', 'Huechuraba', 'Independencia', 'Isla De Maipo', 
'La Cisterna', 'La Florida', 'La Granja', 'La Pintana', 'La Reina', 'Lampa', 'Las Condes', 
'Lo Barnechea', 'Lo Prado', 'Macul', 'Maipu', 'Ñuñoa', 'Pirque', 'Providencia', 'Pudahuel', 
'Puente Alto', 'Recoleta', 'San Bernardo', 'San Joaquín', 'San Miguel', 'San Ramón', 'Santiago',
'Talagante', 'Til Til', 'Vitacura']

export const comunasLista = {
  "Alhué": "https://chat.whatsapp.com/EuAqhxeJfvs8hfLcJGWbFo",
  "Buin": "https://chat.whatsapp.com/KjmYawgfhg52KH1KJR53M7",
  "Calera de Tango": "https://chat.whatsapp.com/CaWPscmHbx0IwInLtpQ4RH",
  "Cerrillos": "https://chat.whatsapp.com/H4tGcHZyUWjCy0h8whqVHy",
  "Colina": "https://chat.whatsapp.com/BUgFVAvHpEV58IsOSuM0Wx",
  "Conchali": "https://chat.whatsapp.com/DXMguTEQ7sY4dhlTWlZyc5",
  "Estación Central": "https://chat.whatsapp.com/CjJTlWEX2xKHay5IfNJY6Z",
  "Independencia": "https://chat.whatsapp.com/Eo90gTlAal4HMfx1DfsmOC",
  "Isla de Maipo": "https://chat.whatsapp.com/IxtzX1kjtLzJPljWeS1upJ",
  "La Cisterna": "https://chat.whatsapp.com/EYqAvTBSb6mJM8LDtCV3WC",
  "La Florida": "https://chat.whatsapp.com/GYRuPeK5iKdCmw2pujv7vA",
  "La Granja": "https://chat.whatsapp.com/Lydz2kj6418B7VuZHW26iD",
  "La Pintana": "https://chat.whatsapp.com/CrELsDFdjxe0o4oUbyxEdY",
  "La Reina": "https://chat.whatsapp.com/JI1pNRVf1PI7yKZAa3tuAH",
  "Las Condes": "https://chat.whatsapp.com/JnhBe2MigygCmTr0nQlznk",
  "Lo Barnechea": "https://chat.whatsapp.com/CY1UkcEwLVeLPnidqMlbb2",
  "Lo Prado": "https://chat.whatsapp.com/Ip3AvR7vAk93pbe74zo8VX",
  "Macul": "https://chat.whatsapp.com/F0dULDoEzS3LWiIlWGrTio",
  "Maipú": "https://chat.whatsapp.com/CvXqGFkw36dCRnvOyVZ02W",
  "María Pinto": "https://chat.whatsapp.com/HFHnl1Nygin7r2IsuXMPjM",
  "Ñuñoa": "https://chat.whatsapp.com/D0f4dQWj99j6SSayFggaJx",
  "Padre Hurtado": "https://chat.whatsapp.com/Jv7ZaM0rzWcIhLOE04Skkp",
  "Pedro Aguirre Cerda": "https://chat.whatsapp.com/FktxYxJsEDy0a9YdTiSX4Z",
  "Peñaflor": "https://chat.whatsapp.com/Cf7SWyiptYDGFlMSn4ZoZR",
  "Peñalolen": "https://chat.whatsapp.com/CjKBbF2jCWTGQSXLYQzNnt",
  "Pirque": "https://chat.whatsapp.com/K8eYzpympoZ2KBzTBXroTS",
  "Providencia": "https://chat.whatsapp.com/LxBqsKps6Kq6B5Jn7losIe",
  "Pudahuel": "https://chat.whatsapp.com/LJ4zKi8jZy2F1jACir1jw9",
  "Puente Alto": "https://chat.whatsapp.com/GnnkLBsDt4B0973zp9BZF8",
  "Quilicura": "https://chat.whatsapp.com/Hmt6OlcxZiVG104hc39amB",
  "Quinta Normal": "https://chat.whatsapp.com/GC7s6FRX7tgFUD87eZoUx1",
  "San Bernardo": "https://chat.whatsapp.com/JvgflMLQs5GJ8rvXjYlwHu",
  "San Joaquín": "https://chat.whatsapp.com/GKOzHO1kuBs4bEOZFtN0oN",
  "San José De Maipo": "https://chat.whatsapp.com/G9IKw90JwRHEeQiay988EC",
  "San Miguel": "https://chat.whatsapp.com/Lwjqy7tvIz7Go7Z3BxPKjW",
  "San Ramón": "https://chat.whatsapp.com/K4xSlG3uvapFHf3QahH6bN",
  "Til Til": "https://chat.whatsapp.com/J9bvcw6ocNIJpmtirbTSS2",
}
